package com.github.maximtereshchenko.clerk.write.api.exception;

public final class UnexpectedResult extends RuntimeException {

    public UnexpectedResult(String message, Throwable cause) {
        super(message, cause);
    }
}
